import { MemberAvatar } from "./MemberAvatar";
import { useState } from "react";
import { Modal } from "./components";
import { calculateExpenseShares, currencyDigits, membersOf, money, normalizeExpense, prepareExpense, splitLabels } from "./ledgerEngine";
import type { Expense, SplitType, Trip } from "./types";
import { uid } from "./types";

export function ExpenseEditor({trip,cityId,initial,onClose,onSave,onAssistant}:{trip:Trip;cityId:string;initial?:Expense;onClose:()=>void;onSave:(expense:Expense)=>void;onAssistant:(text:string)=>void}) {
  const members=membersOf(trip),me=members.find(m=>m.isMe)||members[0];
  const [e,setE]=useState<Expense>(()=>initial?normalizeExpense(initial,members):{id:uid("expense"),title:"",amount:0,currency:trip.expenses[0]?.currency||"EUR",cityId,date:new Intl.DateTimeFormat("sv-SE").format(new Date()),category:"其他",paidBy:me.id,splitType:members.length>1?"equal":"personal",participants:members.map(m=>({memberId:m.id,shares:1})),transactionType:"expense"});
  const [error,setError]=useState(""),[words,setWords]=useState("");
  let shares:Array<{memberId:string;amount:number}>=[],splitError="";
  try{shares=calculateExpenseShares(e,members);}catch(err){splitError=(err as Error).message;}
  function split(type:SplitType){setE({...e,splitType:type,participants:type==="personal"?[{memberId:e.paidBy!}]:e.participants});}
  function submit(event:React.FormEvent){event.preventDefault();try{onSave(prepareExpense(e,members));}catch(err){setError((err as Error).message);}}
  return <Modal title={initial?"确认 / 编辑账单":"记一笔旅行支出"} eyebrow="TRAVEL LEDGER" onClose={onClose}><form className="modal-form ledger-form" onSubmit={submit}>
    <div className="form-row"><label>金额<input autoFocus aria-label="金额" type="number" min="0" step={1/10**currencyDigits(e.currency)} value={e.amount||""} onChange={v=>setE({...e,amount:Number(v.target.value)})} required /></label><label>币种<select value={e.currency} onChange={v=>setE({...e,currency:v.target.value})}>{[...new Set([e.currency,"EUR","CHF","GBP","CZK","HUF","USD","CNY","JPY"])].map(c=><option key={c}>{c}</option>)}</select></label></div>
    <label>用途<input required value={e.title} onChange={v=>setE({...e,title:v.target.value})} placeholder="晚餐、车票或一杯咖啡" /></label>
    <fieldset><legend>{e.transactionType==="refund"?"谁收到退款？":"谁付款？"}</legend><div className="ledger-choices">{members.map(m=><button type="button" key={m.id} aria-pressed={e.paidBy===m.id} onClick={()=>setE({...e,paidBy:m.id})}><MemberAvatar member={m}/> {m.name}</button>)}</div></fieldset>
    <fieldset><legend>怎么分？</legend><div className="ledger-choices">{(["equal","exact","personal"] as SplitType[]).map(t=><button key={t} type="button" aria-pressed={e.splitType===t} onClick={()=>split(t)}>{splitLabels[t]}</button>)}</div><details><summary>更多分账方式</summary><div className="ledger-choices">{(["percentage","shares"] as SplitType[]).map(t=><button key={t} type="button" aria-pressed={e.splitType===t} onClick={()=>split(t)}>{splitLabels[t]}</button>)}</div></details></fieldset>
    <fieldset><legend>谁承担？ · {splitLabels[e.splitType!]}</legend>{members.map(m=>{const p=e.participants?.find(p=>p.memberId===m.id);const field=e.splitType==="exact"?"amount":e.splitType==="percentage"?"percentage":"shares";return <div className="split-person" key={m.id}><label><input type={e.splitType==="personal"?"radio":"checkbox"} name="participant" checked={!!p} onChange={()=>setE({...e,participants:e.splitType==="personal"?[{memberId:m.id}]:p?e.participants!.filter(v=>v.memberId!==m.id):[...(e.participants||[]),{memberId:m.id,shares:1}]})} />{m.name}</label>{p&&["exact","percentage","shares"].includes(e.splitType!)&&<input aria-label={`${m.name} ${splitLabels[e.splitType!]}`} type="number" min="0" step="any" value={p[field]??""} onChange={v=>setE({...e,participants:e.participants!.map(item=>item.memberId===m.id?{...item,[field]:Number(v.target.value)}:item)})} />}<span>{shares.find(s=>s.memberId===m.id)?money(shares.find(s=>s.memberId===m.id)!.amount,e.currency):"—"}</span></div>;})}</fieldset>
    <p role="status">{splitError||`合计：${money(e.amount,e.currency)} / ${money(e.amount,e.currency)} ✓`}</p>
    <details><summary>日期、城市与备注</summary><div className="form-row"><label>日期<input type="date" value={e.date} required onChange={v=>setE({...e,date:v.target.value})}/></label><label>城市<select value={e.cityId} onChange={v=>setE({...e,cityId:v.target.value})}><option value="">未关联城市</option>{trip.cities.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="form-row"><label>分类<select value={e.category} onChange={v=>setE({...e,category:v.target.value as Expense["category"]})}>{["交通","餐饮","住宿","门票","购物","其他"].map(c=><option key={c}>{c}</option>)}</select></label><label>类型<select value={e.transactionType} onChange={v=>setE({...e,transactionType:v.target.value as Expense["transactionType"]})}><option value="expense">支出</option><option value="refund">退款</option></select></label></div><label>备注<textarea value={e.note||""} onChange={v=>setE({...e,note:v.target.value})}/></label></details>
    <details><summary>用一句话让助手记账</summary><textarea value={words} onChange={v=>setWords(v.target.value)} placeholder="晚餐57欧我付的，我和Alex平摊" /><button type="button" disabled={!words.trim()} onClick={()=>onAssistant(words)}>交给旅行助手</button></details>
    {error&&<p role="alert">{error}</p>}<footer><button type="button" onClick={onClose}>取消</button><button className="primary-button" disabled={!!splitError}>确认记账</button></footer>
  </form></Modal>;
}
