import { MemberAvatar, avatarPresets } from "./MemberAvatar";
import { useState } from "react";
import { Modal } from "./components";
import { calculateMemberBalances, calculateSettlements, currencyCode, expenseImpact, membersOf, money, normalizeExpense, splitLabels } from "./ledgerEngine";
import type { Expense, Trip, TripMember } from "./types";
import { uid } from "./types";

export function LedgerView({trip,onAdd,onEdit,onChange}:{trip:Trip;onAdd:()=>void;onEdit:(expense:Expense)=>void;onChange:(trip:Trip)=>void}) {
  const members=membersOf(trip),me=members.find(m=>m.isMe)||members[0];
  const [filter,setFilter]=useState("全部"),[member,setMember]=useState(""),[city,setCity]=useState(""),[currency,setCurrency]=useState("");
  const [panel,setPanel]=useState<""|"members"|"settle"|"filters">(""),[error,setError]=useState("");
  let ledgers:ReturnType<typeof calculateMemberBalances>=[],debts:ReturnType<typeof calculateSettlements>=[],issue="";
  try{ledgers=calculateMemberBalances(trip);debts=calculateSettlements(trip);}catch(e){issue=(e as Error).message;}
  const name=(id:string)=>members.find(m=>m.id===id)?.name||"未知成员";
  const visible=trip.expenses.map(e=>normalizeExpense(e,members)).filter(e=>{
    if(member && e.paidBy!==member&&!e.participants?.some(p=>p.memberId===member))return false;
    if(city&&e.cityId!==city)return false;if(currency&&currencyCode(e.currency)!==currency)return false;
    if(filter==="我付款"&&e.paidBy!==me.id)return false;if(filter==="朋友付款"&&e.paidBy===me.id)return false;
    if(filter==="个人消费"&&e.splitType!=="personal")return false;
    if(filter==="待结算"&&(e.splitType==="personal"||!debts.some(d=>d.currency===currencyCode(e.currency)&&[e.paidBy,...(e.participants||[]).map(p=>p.memberId)].includes(d.fromMemberId))))return false;
    return true;
  }).sort((a,b)=>b.date.localeCompare(a.date));
  function updateMember(id:string,changes:Partial<TripMember>){onChange({...trip,members:members.map(m=>m.id===id?{...m,...changes}:m)});}
  const filterControls = <><div className="ledger-choices">{["全部","我付款","朋友付款","个人消费","待结算"].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="ledger-filter-selects"><select aria-label="筛选成员" value={member} onChange={e=>setMember(e.target.value)}><option value="">全部成员</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><select aria-label="筛选城市" value={city} onChange={e=>setCity(e.target.value)}><option value="">全部城市</option>{trip.cities.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="筛选币种" value={currency} onChange={e=>setCurrency(e.target.value)}><option value="">全部币种</option>{ledgers.map(b=><option key={b.currency}>{b.currency}</option>)}</select></div>{filter==="待结算"&&<small>显示仍有未结清成员余额的共同账单；结算按币种总余额抵扣。</small>}</>;
  return <section className="expenses-page group-ledger"><header className="page-intro row"><div><span className="eyebrow">TRAVEL LEDGER</span><h2>一起旅行，清楚分账</h2><p>谁付了、谁承担，回来轻松结清。</p></div><div className="ledger-choices"><button onClick={()=>setPanel("members")}><span className="avatar-stack">{members.slice(0,4).map(m=><MemberAvatar key={m.id} member={m}/>)}</span>同行人 · {members.length}</button><button onClick={()=>setPanel("settle")}>结算</button><button className="primary-button ledger-add" onClick={onAdd}>＋ 记一笔</button></div></header>
    {issue&&<p role="alert">账目需要检查：{issue}。请编辑对应账单后再结算。</p>}
    <div className="expense-layout"><aside className="expense-summary"><h3>旅行账本</h3>{ledgers.map(b=><section key={b.currency}><small>旅行总支出 · {b.currency}</small><strong>{money(b.total,b.currency)}</strong>{members.map(m=><p key={m.id}><MemberAvatar member={m}/>{m.name} 已支付 <b>{money(b.paid[m.id],b.currency)}</b></p>)}<p><MemberAvatar member={me}/>我应承担 <b>{money(b.shares[me.id],b.currency)}</b></p><h3 className="ledger-balance">{b.balances[me.id]>=0?"我应收":"我应付"} {money(Math.abs(b.balances[me.id]),b.currency)}</h3>{debts.filter(d=>d.currency===b.currency).map((d,i)=><p key={i}><MemberAvatar member={members.find(m=>m.id===d.fromMemberId)}/>{name(d.fromMemberId)} → <MemberAvatar member={members.find(m=>m.id===d.toMemberId)}/>{name(d.toMemberId)} <b>{money(d.amount,d.currency)}</b></p>)}</section>)}<small>{trip.expenses.length} 笔 · 各币种独立结算，不自动换汇</small></aside>
    <div><button className="ledger-mobile-filter" onClick={()=>setPanel("filters")}>筛选账单 · {filter}</button><details className="ledger-filters" open><summary>筛选账单</summary>{filterControls}</details>
    <section className="expense-list">{visible.map(e=>{let impact="";try{impact=expenseImpact(e,members);}catch{impact="分账信息需要修正";}return <article className="ledger-entry" key={e.id}><div><strong>{e.title}</strong><small>{trip.cities.find(c=>c.id===e.cityId)?.name||"旅行"} · {e.date}</small><small>{name(e.paidBy!)} 付款 · {splitLabels[e.splitType!]}{e.splitType==="equal"?` · ${e.participants!.length}人`:""}</small><p>{impact}</p></div><b>{e.transactionType==="refund"?"−":""}{money(e.amount,e.currency)}</b><div className="ledger-entry-actions"><button onClick={()=>onEdit(e)}>编辑</button><button onClick={()=>onEdit({...e,id:uid("expense"),createdAt:undefined,updatedAt:undefined})}>复制</button><button onClick={()=>{if(window.confirm(`删除「${e.title}」？余额会重新计算。`))onChange({...trip,expenses:trip.expenses.filter(v=>v.id!==e.id)});}}>删除</button></div></article>;})}{!visible.length&&<article><div><h3>还没有需要分账的旅行支出</h3><p>记下第一笔共同消费，剩下的交给 Travel Ledger。</p></div></article>}</section></div></div>
    {panel==="filters"&&<Modal title="筛选旅行账单" onClose={()=>setPanel("")}>{filterControls}<button className="primary-button" onClick={()=>setPanel("")}>查看账单</button></Modal>}
    {panel==="members"&&<Modal title="旅行同行人" onClose={()=>setPanel("")}><div className="ledger-members">{members.map(m=><div key={m.id}><MemberAvatar member={m}/><div className="avatar-presets">{avatarPresets.map((avatar,i)=><button type="button" key={avatar} aria-label={`选择头像 ${i+1}`} aria-pressed={m.avatar===avatar} onClick={()=>updateMember(m.id,{avatar})}><MemberAvatar member={{...m,avatar}}/></button>)}</div><input aria-label={`${m.name}的姓名`} value={m.name} onChange={e=>updateMember(m.id,{name:e.target.value})}/><small>{m.isMe?"我":""}</small><label>上传头像<input type="file" accept="image/*" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>4*1024*1024){setError("头像请小于4MB");return;}const reader=new FileReader();reader.onload=()=>updateMember(m.id,{avatar:String(reader.result)});reader.readAsDataURL(file);}}/></label></div>)}</div><button onClick={()=>onChange({...trip,members:[...members,{id:uid("member"),name:`同行人 ${members.length}`,avatar:"🙂",isMe:false}]})}>＋ 添加同行人</button>{error&&<p role="alert">{error}</p>}</Modal>}
    {panel==="settle"&&<Modal title="结算建议" onClose={()=>setPanel("")}><p>各币种独立结算。请实际收付款后再标记，不会删除原始账单。</p>{debts.map((d,i)=><div className="settlement-row" key={i}><strong>{name(d.fromMemberId)} → {name(d.toMemberId)}</strong><b>{money(d.amount,d.currency)}</b><button disabled={!!issue} onClick={()=>{if(window.confirm(`确认已经收到 ${money(d.amount,d.currency)}？`))onChange({...trip,settlements:[...(trip.settlements||[]),{...d,id:uid("settlement"),date:new Intl.DateTimeFormat("sv-SE").format(new Date()),note:"已确认结算"}]});}}>标记为已结算</button></div>)}{!debts.length&&<p>{issue||"目前没有需要结算的余额"}</p>}<h3>已结算记录</h3>{(trip.settlements||[]).map(s=><div className="settlement-row" key={s.id}><span>{s.date} · {name(s.fromMemberId)} → {name(s.toMemberId)} · {money(s.amount,s.currency)}</span><button onClick={()=>{if(window.confirm("撤销这条结算记录？"))onChange({...trip,settlements:trip.settlements?.filter(v=>v.id!==s.id)});}}>撤销</button></div>)}</Modal>}
  </section>;
}
