import { useRef, useState } from "react";
export type PhotoFocus = Record<string, { x: number; y: number }>;
function key(src: string) { let hash=2166136261; for(let i=0;i<src.length;i++)hash=Math.imul(hash^src.charCodeAt(i),16777619);return `${src.length}-${hash>>>0}`; }
export function photoPosition(src: string, focus?: PhotoFocus) { const p=focus?.[key(src)] || {x:50,y:50};return `${p.x}% ${p.y}%`; }
export function PhotoEditor({src,focus,onFocus,onReplace,onRemove,label="图片"}:{src:string;focus?:PhotoFocus;onFocus:(value:PhotoFocus)=>void;onReplace:(src:string)=>void;onRemove:()=>void;label?:string}) {
  const [error,setError]=useState(""); const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
  const p=focus?.[key(src)] || {x:50,y:50};
  const set=(x:number,y:number)=>onFocus({...focus,[key(src)]:{x:Math.max(0,Math.min(100,x)),y:Math.max(0,Math.min(100,y))}});
  return <section className="photo-editor"><div className="photo-editor-crop" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,px:p.x,py:p.y};}} onPointerMove={e=>{if(drag.current){const box=e.currentTarget.getBoundingClientRect();set(drag.current.px-(e.clientX-drag.current.x)/box.width*100,drag.current.py-(e.clientY-drag.current.y)/box.height*100);}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><img draggable={false} src={src} alt={label} style={{objectPosition:photoPosition(src,focus)}}/></div><small>拖动图片调整取景，或使用滑杆。保留完整原图。</small><label>左右<input aria-label={`${label}左右取景`} type="range" min="0" max="100" value={p.x} onChange={e=>set(Number(e.target.value),p.y)}/></label><label>上下<input aria-label={`${label}上下取景`} type="range" min="0" max="100" value={p.y} onChange={e=>set(p.x,Number(e.target.value))}/></label><div className="photo-editor-actions"><label>替换图片<input aria-label={`替换${label}`} type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;if(!file.type.startsWith("image/")||file.size>15*1024*1024){setError("请选择15MB以内的图片");return;}const reader=new FileReader();reader.onload=()=>{setError("");onReplace(String(reader.result));};reader.onerror=()=>setError("图片读取失败");reader.readAsDataURL(file);}}/></label><button type="button" onClick={()=>set(50,50)}>居中</button><button type="button" onClick={onRemove}>删除图片</button></div>{error&&<p role="alert">{error}</p>}</section>;
}
