import type { TravelDocument } from "./types";

export const sampleDocument: TravelDocument = {
  version: 1,
  activeTripId: "europe-2026",
  trips: [
    {
      id: "europe-2026",
      title: "欧洲之行",
      startDate: "2026.09.24",
      endDate: "2026.10.06",
      subtitle: "布鲁塞尔 · 科隆 · 瑞士 · 萨尔茨堡 · 维也纳",
      updatedAt: new Date().toISOString(),
      track: {
        title: "Lazy Sunday",
        artist: "Chill Vibes",
        reason: "给城市漫步留一点松弛的拍子。",
        url: "https://music.apple.com/cn/search?term=Lazy%20Sunday%20Chill%20Vibes",
      },
      cities: [
        {
          id: "brussels",
          name: "布鲁塞尔",
          englishName: "Brussels",
          dates: "9.24 – 9.25",
          note: "大广场、漫画墙与一杯傍晚的 Lambic。",
          color: "#f0ddc5",
          days: [
            {
              id: "bru-day-1",
              date: "9.24",
              weekday: "周四",
              title: "抵达与老城散步",
              places: [
                {
                  id: "grand-place",
                  name: "布鲁塞尔大广场",
                  category: "景点",
                  time: "15:00",
                  endTime: "16:30",
                  summary: "从市政厅尖塔开始读懂布鲁塞尔，黄昏时金色立面最有层次。",
                  highlights: ["市政厅尖塔", "行会建筑", "蓝调时刻"],
                  duration: "1.5 小时",
                  mapUrl: "https://maps.apple.com/?q=Grand+Place+Brussels",
                },
                {
                  id: "manneken-pis",
                  name: "撒尿小童",
                  category: "景点",
                  time: "16:40",
                  endTime: "17:10",
                  summary: "老城最顽皮的小地标，适合与附近漫画墙一起串成轻松步行线。",
                  highlights: ["城市轶事", "限定服装", "漫画墙"],
                  duration: "30 分钟",
                  mapUrl: "https://maps.apple.com/?q=Manneken+Pis",
                },
                {
                  id: "fin-de-siecle",
                  name: "Fin de Siècle",
                  category: "美食",
                  time: "18:00",
                  endTime: "19:30",
                  summary: "份量豪爽的比利时家常菜，适合用炖牛肉收尾抵达日。",
                  highlights: ["啤酒炖牛肉", "本地啤酒", "不接受预约"],
                  duration: "1.5 小时",
                  mapUrl: "https://www.google.com/maps/search/?api=1&query=Fin+de+Siecle+Brussels",
                },
              ],
            },
            {
              id: "bru-day-2",
              date: "9.25",
              weekday: "周五",
              title: "亚琛一日与科隆夜景",
              places: [
                {
                  id: "aachen-cathedral",
                  name: "亚琛大教堂",
                  category: "景点",
                  time: "10:30",
                  endTime: "12:00",
                  summary: "八角形礼拜堂的马赛克穹顶，是查理曼时代最直观的一页。",
                  highlights: ["八角穹顶", "查理曼圣龛", "马赛克"],
                  duration: "1.5 小时",
                },
              ],
            },
          ],
        },
        {
          id: "cologne",
          name: "科隆 / 亚琛",
          englishName: "Cologne / Aachen",
          dates: "9.25",
          note: "教堂、铁路与莱茵河边的一段过场。",
          color: "#e7dfc9",
          days: [],
        },
        {
          id: "swiss",
          name: "瑞士山区",
          englishName: "Lungern / Montreux",
          dates: "9.26 – 10.01",
          note: "湖、山间列车和需要留白的天气。",
          color: "#dce7d2",
          days: [
            {
              id: "swiss-day-1",
              date: "9.27",
              weekday: "周日",
              title: "伯尔尼一日游",
              places: [
                {
                  id: "bern-old-town",
                  name: "伯尔尼老城",
                  category: "景点",
                  time: "10:00",
                  endTime: "12:00",
                  summary: "沿六公里拱廊慢慢走，钟楼、喷泉与砂岩立面形成统一节奏。",
                  highlights: ["钟楼报时", "拱廊", "玫瑰园远眺"],
                  duration: "2 小时",
                },
                {
                  id: "kornhauskeller",
                  name: "Kornhauskeller",
                  category: "美食",
                  time: "12:30",
                  endTime: "14:00",
                  summary: "在华丽穹顶下吃一顿瑞士午餐，本身就像参观一处室内景点。",
                  highlights: ["历史穹顶", "伯尔尼拼盘", "提前订位"],
                  duration: "1.5 小时",
                },
                {
                  id: "rose-garden",
                  name: "玫瑰园",
                  category: "景点",
                  time: "15:00",
                  endTime: "16:30",
                  summary: "俯瞰阿勒河环抱老城的经典机位，下午光线更适合拍照。",
                  highlights: ["老城全景", "阿勒河弯", "日落"],
                  duration: "1.5 小时",
                },
              ],
            },
          ],
        },
        {
          id: "salzburg",
          name: "萨尔茨堡",
          englishName: "Salzburg",
          dates: "10.02 – 10.04",
          note: "城堡、巴洛克屋顶和一点莫扎特。",
          color: "#eadccf",
          days: [],
        },
      ],
      tickets: [
        {
          id: "sbb-ticket",
          kind: "火车票",
          cityId: "salzburg",
          provider: "SBB Train",
          title: "Zürich HB → Salzburg Hbf",
          date: "2026-10-02",
          time: "08:32 → 15:02",
          meta: "Coach 34 · Seat 54 / 56",
          code: "RJX 165",
          color: "#efd5cf",
        },
        {
          id: "hotel-ticket",
          kind: "酒店",
          cityId: "salzburg",
          provider: "Hi Salzburg Hotel",
          title: "Salzburg · 2 nights",
          date: "2026-10-02",
          time: "Check-in 15:00",
          meta: "Twin · Check-out 10.04",
          code: "HS-88217",
          color: "#efe2bd",
        },
        {
          id: "palace-ticket",
          kind: "门票",
          cityId: "salzburg",
          provider: "Schönbrunn Palace",
          title: "Grand Tour",
          date: "2026-10-04",
          time: "10:00",
          meta: "Adult · 1 guest",
          code: "VIE-0410",
          color: "#dbe7d5",
        },
      ],
      expenses: [
        { id: "exp-1", cityId: "brussels", date: "2026-09-24", title: "机场到市区", amount: 45, currency: "€", category: "交通" },
        { id: "exp-2", cityId: "brussels", date: "2026-09-24", title: "晚餐", amount: 28.5, currency: "€", category: "餐饮" },
        { id: "exp-3", cityId: "brussels", date: "2026-09-25", title: "博物馆门票", amount: 13, currency: "€", category: "门票" },
      ],
      chats: [
        {
          id: "welcome",
          role: "assistant",
          content: "你好，我会陪你整理地点、顺路安排行程，也可以帮你补上每一站的看点。",
          createdAt: new Date().toISOString(),
        },
      ],
    },
  ],
};

export const tripTracks = [
  { title: "La vie en rose", artist: "Édith Piaf", reason: "老城与火车窗景都适合一点法式旧唱片感。" },
  { title: "A Walk", artist: "Tycho", reason: "适合在湖边和城市之间缓慢移动。" },
  { title: "Friday Morning", artist: "Khruangbin", reason: "轻松、松弛，又有一点公路旅行的摇晃。" },
  { title: "Sunset Lover", artist: "Petit Biscuit", reason: "留给傍晚车窗与蓝调时刻。" },
  { title: "Hoppípolla", artist: "Sigur Rós", reason: "当山景突然铺开时，音乐也跟着变得宽阔。" },
];
