import { useMemo, useState } from "react";
import type { Ticket, Trip } from "./types";
import { TicketCard, Modal } from "./components";
import { sortTickets, ticketAttachments } from "./tickets";

export function TicketsView({ trip, onAdd, onEdit, onRemove, onExport }: { trip: Trip; onAdd: () => void; onEdit: (id: string) => void; onRemove: (id: string) => void; onExport: () => void }) {
  const [layout, setLayout] = useState<"cards" | "list">("cards");
  const [preview, setPreview] = useState<Ticket | null>(null);
  const tickets = useMemo(() => sortTickets(trip.tickets, trip.startDate), [trip.tickets, trip.startDate]);
  return <section className="tickets-page"><header className="page-intro row"><div><span className="eyebrow">TICKET POCKET</span><h2>一路收好的票据</h2><p>按日期与出发时间排列。带上完整票夹，离线也能查看。</p></div><div className="ticket-page-actions"><button onClick={onExport}>⇩ 离线 HTML</button><div className="ticket-view-toggle" aria-label="票据显示方式"><button className={layout === "cards" ? "active" : ""} onClick={() => setLayout("cards")}>▦ 卡片</button><button className={layout === "list" ? "active" : ""} onClick={() => setLayout("list")}>☷ 列表</button></div><button className="primary-button" onClick={onAdd}>＋ 添加票据</button></div></header>
    {layout === "cards" ? <div className="ticket-grid">{tickets.map((ticket) => <TicketCard key={ticket.id} ticket={ticket} city={trip.cities.find((city) => city.id === ticket.cityId)} onEdit={() => onEdit(ticket.id)} onRemove={() => onRemove(ticket.id)} onPreview={() => setPreview(ticket)} />)}</div> : <div className="ticket-list">{tickets.map((ticket) => <article key={ticket.id}><time>{ticket.checkInDate || ticket.date}</time><span className="ticket-list-kind">{ticket.kind}</span><div><strong>{ticket.title}{ticket.kind === "酒店" && ticket.includesBreakfast && <span className="breakfast-list-icon"><img src="./assets/breakfast-croissant.png" alt="含早餐" /></span>}</strong><small>{ticket.passengers || ticket.provider}</small></div><p>{ticket.time}<small>{ticket.meta}</small></p><div className="ticket-list-actions"><button aria-label={`预览${ticket.title}`} onClick={() => setPreview(ticket)}>▣</button><button aria-label={`编辑${ticket.title}`} onClick={() => onEdit(ticket.id)}>✎</button><button aria-label={`删除${ticket.title}`} onClick={() => onRemove(ticket.id)}>×</button></div></article>)}</div>}
    {!tickets.length && <div className="empty-state"><h3>票据夹还是空的</h3><button onClick={onAdd}>＋ 添加第一张票据</button></div>}
    {preview && <Modal title={preview.title} eyebrow="完整票据" wide onClose={() => setPreview(null)}><div className="ticket-full-preview">{preview.qrCode && <section><h3>二维码</h3><img className="full-qr" src={preview.qrCode} alt="完整二维码" /></section>}{ticketAttachments(preview).map((file) => <section key={file.id}><h3>{file.name}</h3><a href={file.data} download={file.name}>保存原始文件</a>{file.type === "image" ? <img src={file.data} alt={file.name} /> : file.pages?.length ? file.pages.map((page, index) => <figure key={index}><img src={page} alt={`${file.name} 第 ${index + 1} 页`} /><figcaption>第 {index + 1} / {file.pages!.length} 页</figcaption></figure>) : <iframe src={file.data} title={file.name} />}</section>)}</div></Modal>}
  </section>;
}
